"""
Seed data for EventFlow SQLite database.
Ported from server/seedData.js.
"""

organizers = [
    {
        "id": "org-1",
        "name": "Aarav Sharma",
        "email": "aarav.lead@campus.edu",
        "department": "Computer Science & Engineering",
        "role": "Tech Club President",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    },
    {
        "id": "org-2",
        "name": "Priya Iyer",
        "email": "priya.cultural@campus.edu",
        "department": "Media & Fine Arts",
        "role": "Cultural Council Head",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    },
    {
        "id": "org-3",
        "name": "Rohan Deshmukh",
        "email": "rohan.robotics@campus.edu",
        "department": "Mechanical & Mechatronics",
        "role": "Robotics Society Lead",
        "avatar_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    },
    {
        "id": "org-4",
        "name": "Sneha Verma",
        "email": "sneha.sports@campus.edu",
        "department": "Physical Education",
        "role": "Sports Secretary",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    },
]

events = [
    {
        "id": "evt-1",
        "organizer_id": "org-1",
        "title": "TechTrove Hackathon 2026",
        "description": "The flagship 24-hour inter-college hackathon bringing together visionary developers, designers, and innovators to solve high-impact real-world challenges across AI, Web3, and GreenTech.",
        "category": "Hackathon",
        "venue": "Main Convention Center",
        "date": "2026-10-15",
        "start_time": "09:00 AM",
        "end_time": "05:00 PM (Next Day)",
        "registration_deadline": "2026-10-12",
        "capacity": 120,
        "registered_count": 88,
        "banner_url": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=80",
        "coordinator_name": "Aarav Sharma",
        "coordinator_contact": "+91 98765 43210",
        "status": "upcoming",
    },
    {
        "id": "evt-2",
        "organizer_id": "org-3",
        "title": "RoboWars: Steel Gladiators",
        "description": "Custom-built heavyweight combat robotics fighting tournament in an enclosed steel arena. Watch high-torque bot battles featuring spinners, lifters, and pneumatic axes.",
        "category": "Technical",
        "venue": "Indoor Sports Arena",
        "date": "2026-10-18",
        "start_time": "10:00 AM",
        "end_time": "04:00 PM",
        "registration_deadline": "2026-10-15",
        "capacity": 80,
        "registered_count": 64,
        "banner_url": "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80",
        "coordinator_name": "Rohan Deshmukh",
        "coordinator_contact": "+91 98765 12345",
        "status": "upcoming",
    },
    {
        "id": "evt-3",
        "organizer_id": "org-2",
        "title": "Cadence Annual Cultural Gala",
        "description": "An electrifying celebration of campus talent featuring the Battle of the Bands, inter-college choreography showdowns, theatrical drama, and a high-fashion runway.",
        "category": "Cultural",
        "venue": "Open Air Amphitheatre",
        "date": "2026-10-22",
        "start_time": "05:00 PM",
        "end_time": "11:00 PM",
        "registration_deadline": "2026-10-20",
        "capacity": 300,
        "registered_count": 215,
        "banner_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80",
        "coordinator_name": "Priya Iyer",
        "coordinator_contact": "+91 98111 22334",
        "status": "upcoming",
    },
    {
        "id": "evt-4",
        "organizer_id": "org-1",
        "title": "GenAI & Cloud Architecture Bootcamp",
        "description": "A deep-dive hands-on workshop building production agentic AI systems with LLMs, vector search, cloud serverless microservices, and automated CI/CD pipelines.",
        "category": "Workshop",
        "venue": "High Performance Computing Lab",
        "date": "2026-10-25",
        "start_time": "09:30 AM",
        "end_time": "03:30 PM",
        "registration_deadline": "2026-10-23",
        "capacity": 60,
        "registered_count": 52,
        "banner_url": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80",
        "coordinator_name": "Vikram Joshi",
        "coordinator_contact": "+91 97222 33445",
        "status": "upcoming",
    },
    {
        "id": "evt-5",
        "organizer_id": "org-4",
        "title": "Inter-College Badminton Open",
        "description": "Annual smash championship featuring competitive singles and doubles divisions across men’s and women’s brackets. Trophies, medals, and cash prizes for champions.",
        "category": "Sports",
        "venue": "Student Activity Sports Complex",
        "date": "2026-10-28",
        "start_time": "08:00 AM",
        "end_time": "06:00 PM",
        "registration_deadline": "2026-10-26",
        "capacity": 50,
        "registered_count": 38,
        "banner_url": "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&auto=format&fit=crop&q=80",
        "coordinator_name": "Sneha Verma",
        "coordinator_contact": "+91 99888 77665",
        "status": "upcoming",
    },
    {
        "id": "evt-6",
        "organizer_id": "org-1",
        "title": "Future of Quantum Computing & AI Ethics",
        "description": "Distinguished lecture and panel discussion featuring industry researchers on fault-tolerant quantum algorithms, cryogenic hardware, and AI governance policies.",
        "category": "Seminar",
        "venue": "Tech Auditorium Hall B",
        "date": "2026-11-02",
        "start_time": "11:00 AM",
        "end_time": "02:00 PM",
        "registration_deadline": "2026-10-31",
        "capacity": 150,
        "registered_count": 95,
        "banner_url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80",
        "coordinator_name": "Dr. Ananya Ray",
        "coordinator_contact": "+91 98444 55667",
        "status": "upcoming",
    },
]

event_sessions = [
    # Sessions for TechTrove Hackathon
    {
        "id": "ses-1",
        "event_id": "evt-1",
        "round_name": "Round 1: Problem Pitch & Idea Screening",
        "venue_room": "Seminar Hall A",
        "start_time": "09:30 AM",
        "end_time": "11:30 AM",
        "description": "Teams present their chosen problem statement, architecture overview, and target deliverable to industry mentors.",
        "order_index": 1,
    },
    {
        "id": "ses-2",
        "event_id": "evt-1",
        "round_name": "Round 2: 24-Hour Prototype Sprint & Midnight Check-in",
        "venue_room": "Innovation Lab 301",
        "start_time": "12:00 PM",
        "end_time": "08:00 AM (Next Day)",
        "description": "Intensive coding session with mentor desk reviews at 6 PM, 12 AM, and 6 AM for milestone verification.",
        "order_index": 2,
    },
    {
        "id": "ses-3",
        "event_id": "evt-1",
        "round_name": "Round 3: Grand Finale Demo & Jury Evaluation",
        "venue_room": "Grand Auditorium",
        "start_time": "10:00 AM",
        "end_time": "02:00 PM",
        "description": "Top 10 finalist teams showcase live working software followed by Q&A with tech judges and prize awards.",
        "order_index": 3,
    },
    # Sessions for RoboWars
    {
        "id": "ses-4",
        "event_id": "evt-2",
        "round_name": "Round 1: Technical & Safety Scrutiny",
        "venue_room": "Mechanical Workshop 102",
        "start_time": "10:00 AM",
        "end_time": "11:30 AM",
        "description": "Bot weigh-in, fail-safe radio check, weapon lock verification, and battery safety certification.",
        "order_index": 1,
    },
    {
        "id": "ses-5",
        "event_id": "evt-2",
        "round_name": "Round 2: 1v1 Elimination Heats",
        "venue_room": "Central Combat Cage",
        "start_time": "12:00 PM",
        "end_time": "02:30 PM",
        "description": "3-minute brutal face-offs with hazard traps, spikes, and pit drops.",
        "order_index": 2,
    },
    {
        "id": "ses-6",
        "event_id": "evt-2",
        "round_name": "Round 3: Championship Deathmatch",
        "venue_room": "Central Combat Cage",
        "start_time": "03:00 PM",
        "end_time": "04:00 PM",
        "description": "Grand final clash for the trophy and the Title of Titan.",
        "order_index": 3,
    },
    # Sessions for Cadence Cultural Fest
    {
        "id": "ses-7",
        "event_id": "evt-3",
        "round_name": "Session 1: Battle of the Bands",
        "venue_room": "Acoustic Stage Left",
        "start_time": "05:00 PM",
        "end_time": "07:30 PM",
        "description": "Rock, fusion, and indie live music competition by campus bands.",
        "order_index": 1,
    },
    {
        "id": "ses-8",
        "event_id": "evt-3",
        "round_name": "Session 2: Synchronized Dance & Drama",
        "venue_room": "Center Amphitheatre Stage",
        "start_time": "07:45 PM",
        "end_time": "09:45 PM",
        "description": "Inter-collegiate mega crews showcase energetic thematic performances.",
        "order_index": 2,
    },
    {
        "id": "ses-9",
        "event_id": "evt-3",
        "round_name": "Session 3: Celebrity DJ Night & Finale",
        "venue_room": "Amphitheatre Ground",
        "start_time": "10:00 PM",
        "end_time": "11:00 PM",
        "description": "High-energy musical closing celebration for all attendees.",
        "order_index": 3,
    },
    # Sessions for GenAI Workshop
    {
        "id": "ses-10",
        "event_id": "evt-4",
        "round_name": "Part 1: Building LLM Agents with Tool Use",
        "venue_room": "Lab 402 - Terminal Wing",
        "start_time": "09:30 AM",
        "end_time": "12:00 PM",
        "description": "Architecture of reasoning loops, function calling, and structured output parsing.",
        "order_index": 1,
    },
    {
        "id": "ses-11",
        "event_id": "evt-4",
        "round_name": "Part 2: Production Deployment & Observability",
        "venue_room": "Lab 402 - Terminal Wing",
        "start_time": "01:00 PM",
        "end_time": "03:30 PM",
        "description": "Containerizing agents, tracing latency, token streaming, and cloud deployment.",
        "order_index": 2,
    },
]

# Aliases
eventSessions = event_sessions

sample_registrations = [
    {
        "id": "reg-1",
        "event_id": "evt-1",
        "ticket_code": "EVF-2026-X801",
        "participant_name": "Aditya Nair",
        "email": "aditya.nair@college.edu",
        "phone": "+91 98451 12345",
        "college": "National Institute of Technology",
        "department": "Computer Science & Engineering",
        "year_of_study": "3rd Year",
        "status": "checked_in",
    },
    {
        "id": "reg-2",
        "event_id": "evt-1",
        "ticket_code": "EVF-2026-X802",
        "participant_name": "Meera Krishnan",
        "email": "meera.k@college.edu",
        "phone": "+91 98452 23456",
        "college": "National Institute of Technology",
        "department": "Information Technology",
        "year_of_study": "4th Year",
        "status": "registered",
    },
    {
        "id": "reg-3",
        "event_id": "evt-1",
        "ticket_code": "EVF-2026-X803",
        "participant_name": "Karthik Raja",
        "email": "karthik.r@college.edu",
        "phone": "+91 98453 34567",
        "college": "PSG College of Technology",
        "department": "Electronics & Communication",
        "year_of_study": "2nd Year",
        "status": "checked_in",
    },
    {
        "id": "reg-4",
        "event_id": "evt-2",
        "ticket_code": "EVF-2026-X804",
        "participant_name": "Siddharth Menon",
        "email": "sid.menon@college.edu",
        "phone": "+91 98454 45678",
        "college": "College of Engineering Guindy",
        "department": "Mechanical Engineering",
        "year_of_study": "3rd Year",
        "status": "registered",
    },
    {
        "id": "reg-5",
        "event_id": "evt-2",
        "ticket_code": "EVF-2026-X805",
        "participant_name": "Tanvi Saxena",
        "email": "tanvi.s@college.edu",
        "phone": "+91 98455 56789",
        "college": "Vellore Institute of Technology",
        "department": "Mechatronics",
        "year_of_study": "4th Year",
        "status": "checked_in",
    },
    {
        "id": "reg-6",
        "event_id": "evt-3",
        "ticket_code": "EVF-2026-X806",
        "participant_name": "Ananya Roy",
        "email": "ananya.roy@college.edu",
        "phone": "+91 98456 67890",
        "college": "St. Xavier’s College",
        "department": "Media Studies",
        "year_of_study": "2nd Year",
        "status": "registered",
    },
    {
        "id": "reg-7",
        "event_id": "evt-4",
        "ticket_code": "EVF-2026-X807",
        "participant_name": "Rahul Varma",
        "email": "rahul.varma@college.edu",
        "phone": "+91 98457 78901",
        "college": "National Institute of Technology",
        "department": "Computer Science & Engineering",
        "year_of_study": "3rd Year",
        "status": "checked_in",
    },
    {
        "id": "reg-8",
        "event_id": "evt-5",
        "ticket_code": "EVF-2026-X808",
        "participant_name": "Devika Pillai",
        "email": "devika.p@college.edu",
        "phone": "+91 98458 89012",
        "college": "Madras Christian College",
        "department": "Civil Engineering",
        "year_of_study": "1st Year",
        "status": "registered",
    },
]

# Aliases
sampleRegistrations = sample_registrations

announcements = [
    {
        "id": "anc-1",
        "event_id": "evt-1",
        "title": "Hackathon Round 2 Lab Reassignment",
        "message": "Due to network capacity upgrades, Round 2 Prototype Sprint has been relocated to Innovation Lab 301. High-speed gigabit Wi-Fi and power strips are available at each team bench.",
        "priority": "urgent",
        "published_by": "Aarav Sharma (Club Lead)",
    },
    {
        "id": "anc-2",
        "event_id": None,  # Campus-wide
        "title": "Welcome to TechTrove Campus Fest 2026!",
        "message": "Welcome to all participants! The central registration and assistance kiosk is located right at the Main Administration Quad. Download your digital passes in the My Tickets tab.",
        "priority": "info",
        "published_by": "Campus Event Coordination Cell",
    },
    {
        "id": "anc-3",
        "event_id": "evt-2",
        "title": "RoboWars Arena Safety Briefing",
        "message": "All combat robotics operators must report with their robots for technical inspection at 10:00 AM sharp at Workshop 102. Safety glasses mandatory in the pit area.",
        "priority": "update",
        "published_by": "Rohan Deshmukh",
    },
    {
        "id": "anc-4",
        "event_id": "evt-3",
        "title": "CADENCE Cultural Gala Entry Guidelines",
        "message": "Gates for the Open Air Amphitheatre open at 04:30 PM. Please present your digital QR pass on your phone for rapid barcode scanning.",
        "priority": "info",
        "published_by": "Priya Iyer",
    },
]
